[
  ./wm/hyprland
  ./terminal/shell/zsh
  ./terminal/programs/rust.nix
  ./terminal/programs/home-manager.nix
  ./terminal/programs/github.nix
  ./terminal/programs/nix.nix
  ./terminal/programs/fzf.nix
  ./terminal/programs/newsboat.nix
  ./terminal/programs/git.nix
  ./terminal/programs/direnv.nix
  ./terminal/programs/bat.nix
  ./terminal/programs/terraform.nix
  ./terminal/programs/btop.nix
  ./terminal/programs/tmux.nix
  ./terminal/programs/k8s-cli.nix
  ./terminal/programs/ssh.nix
  ./terminal/emulator/alacritty.nix
  ./os
  ./os/nixos
  ./os/darwin
  ./hackstation.nix
  ./graphical/browser/firefox.nix
  ./graphical/programs/gtk.nix
  ./graphical/programs/zathura.nix
  ./graphical/programs/rofi
  ./graphical/services/mako.nix
]
